name: Deploy to Surge

# Déclenche le déploiement à chaque push sur la branche main
on:
  workflow_dispatch:
  push:
    branches: "main"

# N'autorise un seul déploiement à la fois
concurrency:
  group: "surge"
  cancel-in-progress: true
  
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: projet/frontend
    steps:
      # Récupère le code à jour
      - name: Checkout
        uses: actions/checkout@v3
      
      # Installe les dépendances
      - name: Install dependencies
        run: npm ci
        
      # Build le site
      - name: Build
        run: npm run build

      # Envoie le site sur Surge
      - name: Deploy
        run: |
          npm install -g surge
          surge --project ./dist --token ${{ secrets.SURGE_TOKEN }}
